const menuItems = [
  {
    id: 1,
    name: "Ayam Bakar",
    category: "main",
    price: 18000,
    image: "assets/menu/split-image-10.jpg",
    description: "Ayam bakar + tahu + tempe + sambal.",
    tags: ["Makanan", "Ayam", "Sambal"],
  },
  {
    id: 2,
    name: "Ayam Goreng",
    category: "main",
    price: 18000,
    image: "assets/menu/split-image-12.jpg",
    description: "Ayam goreng + tahu + tempe + sambal.",
    tags: ["Makanan", "Ayam", "Sambal"],
  },
  {
    id: 3,
    name: "Ayam Geprek",
    category: "main",
    price: 15000,
    image: "assets/menu/split-image-11.jpg",
    description: "Ayam crispy + sambal. Pilihan sambal: geprek atau matah.",
    tags: ["Makanan", "Ayam", "Pedas"],
  },
  {
    id: 4,
    name: "Ayam Rempah",
    category: "main",
    price: 18000,
    image: "assets/menu/split-image-12.jpg",
    description: "Ayam rempah + tahu + tempe + sambal.",
    tags: ["Makanan", "Ayam", "Rempah"],
  },
  {
    id: 5,
    name: "Nasi Putih",
    category: "main",
    price: 4000,
    image: "assets/menu/split-image-7.jpg",
    description: "Nasi putih hangat untuk pelengkap makan.",
    tags: ["Makanan", "Nasi"],
  },
  {
    id: 6,
    name: "Nasi Goreng",
    category: "main",
    price: 12000,
    image: "assets/menu/split-image-9.jpg",
    description: "Nasi goreng + telor.",
    tags: ["Makanan", "Nasi", "Telor"],
  },
  {
    id: 7,
    name: "Nasi Telor",
    category: "main",
    price: 11000,
    image: "assets/menu/split-image-8.jpg",
    description: "Nasi + telor + sambal.",
    tags: ["Makanan", "Nasi", "Telor"],
  },
  {
    id: 8,
    name: "Mie Kuah",
    category: "main",
    price: 7000,
    image: "assets/menu/split-image-5.jpg",
    description: "Mie kuah hangat dan praktis.",
    tags: ["Makanan", "Mie"],
  },
  {
    id: 9,
    name: "Mie Goreng",
    category: "main",
    price: 7000,
    image: "assets/menu/split-image-6.jpg",
    description: "Mie goreng praktis dengan rasa gurih.",
    tags: ["Makanan", "Mie"],
  },
  {
    id: 10,
    name: "Extra Telur",
    category: "main",
    price: 4000,
    image: "assets/menu/ekstra_telur.jpeg",
    description: "Tambahan telur untuk mie kuah atau mie goreng.",
    tags: ["Tambahan", "Telur"],
  },
  {
    id: 11,
    name: "Kentang Goreng",
    category: "snack",
    price: 12000,
    image: "assets/menu/split-image-1.jpeg",
    description: "Kentang goreng renyah untuk teman santai.",
    tags: ["Snack", "Gorengan"],
  },
  {
    id: 12,
    name: "Sosis Goreng",
    category: "snack",
    price: 7000,
    image: "assets/menu/split-image-2.jpeg",
    description: "Sosis goreng hangat dengan rasa gurih.",
    tags: ["Snack", "Gorengan"],
  },
  {
    id: 13,
    name: "Nugget Goreng",
    category: "snack",
    price: 7000,
    image: "assets/menu/split-image-3.jpeg",
    description: "Nugget goreng praktis dan cocok untuk camilan.",
    tags: ["Snack", "Gorengan"],
  },
  {
    id: 14,
    name: "Mix Platter",
    category: "snack",
    price: 20000,
    image: "assets/menu/split-image-4.jpg",
    description: "Paket snack campur untuk dimakan bersama.",
    tags: ["Snack", "Sharing"],
  },
  {
    id: 15,
    name: "Teh Hangat / Es",
    category: "drink",
    price: 4000,
    image: "assets/menu/minuman-teh.jpeg",
    description: "Teh hangat atau es teh segar.",
    tags: ["Minuman", "Teh"],
  },
  {
    id: 16,
    name: "Jeruk Hangat / Es",
    category: "drink",
    price: 6000,
    image: "assets/menu/minuman-jeruk.png",
    description: "Jeruk hangat atau es jeruk segar.",
    tags: ["Minuman", "Jeruk"],
  },
  {
    id: 17,
    name: "Kopi Hitam Panas",
    category: "drink",
    price: 5000,
    image: "assets/menu/minuman-kopi-hitam.jpeg",
    description: "Kopi hitam panas dengan rasa klasik.",
    tags: ["Minuman", "Kopi"],
  },
  {
    id: 18,
    name: "Nutrisari",
    category: "drink",
    price: 4000,
    image: "assets/menu/minuman-nutrisari.jpeg",
    description: "Minuman rasa buah yang segar.",
    tags: ["Minuman", "Segar"],
  },
  {
    id: 19,
    name: "Milo",
    category: "drink",
    price: 5000,
    image: "assets/menu/minuman-milo.jpeg",
    description: "Minuman cokelat malt favorit.",
    tags: ["Minuman", "Cokelat"],
  },
  {
    id: 20,
    name: "Good Day",
    category: "drink",
    price: 5000,
    image: "assets/menu/minuman-good-day.png",
    description: "Kopi Good Day pilihan.",
    tags: ["Minuman", "Kopi"],
  },
  {
    id: 21,
    name: "Air Es",
    category: "drink",
    price: 2000,
    image: "assets/menu/minuman-air-es.jpeg",
    description: "Air es dingin dan menyegarkan.",
    tags: ["Minuman", "Air"],
  },
  {
    id: 22,
    name: "Es Kopi Gula Aren",
    category: "drink",
    price: 10000,
    image: "assets/menu/minuman-kopi-gula-aren.jpeg",
    description: "Es kopi dengan rasa manis gula aren.",
    tags: ["Minuman", "Kopi", "Dingin"],
  },
  {
    id: 23,
    name: "Es Kopi Hazelnut",
    category: "drink",
    price: 10000,
    image: "assets/menu/minuman-kopi-hazelnut.jpeg",
    description: "Es kopi dengan aroma hazelnut.",
    tags: ["Minuman", "Kopi", "Dingin"],
  },
  {
    id: 24,
    name: "Lemon Tea",
    category: "drink",
    price: 8000,
    image: "assets/menu/minuman-lemon-tea.jpeg",
    description: "Teh lemon segar dengan rasa ringan.",
    tags: ["Minuman", "Teh", "Segar"],
  },
  {
    id: 25,
    name: "Es Cokelat",
    category: "drink",
    price: 8000,
    image: "assets/menu/minuman-es-cokelat.jpeg",
    description: "Minuman cokelat dingin.",
    tags: ["Minuman", "Cokelat", "Dingin"],
  },
  {
    id: 26,
    name: "Taro / Red Velvet Ice",
    category: "drink",
    price: 8000,
    image: "assets/menu/minuman-taro-redvelvet.png",
    description: "Pilihan taro atau red velvet ice.",
    tags: ["Minuman", "Dingin"],
  },
];

globalThis.menuItems = menuItems;
